### ISSUE TITLE
1

### ISSUE THREAD

**Issue by iam-py-test** [spirillen/templatetest#6]
### Domain/URL/IP(s) you believe NOT to be Phishing

```css
127.0.0.1
```

### More Information

- [X] mitchellkrogza Phishing
- [X] mitchellkrogza Phishing.Database
- [X] Website was hacked
- [X] Listed as Phishing on Phishtank or OpenPhish
- [X] Listed on VirusTotal
- [X] Other (Please tell us where in *Related external source* below)

### Related external source

```["markdown"]
http://localhost/i-m-not-a-phish-trust-me
```

### Describe the issue

127.0.0.1 is MY WEBSITE. Unblock it nows.

**Comment by spirillen** [comment]
> 127.0.0.1 is MY WEBSITE. Unblock it nows.

No it is MY website, don't you dare to steel it :rofl:

**Comment by iam-py-test** [comment]
Well, the template looks ok

**Comment by spirillen** [comment]
Super, lets see what @funilrys says in https://github.com/mitchellkrogza/phishing/pull/98

PS: did you got time to have a peak on the readme's over at https://mypdns.org/clefspeare13/pornhosts

**Comment by iam-py-test** [comment]
> Super, lets see what @funilrys says in [mitchellkrogza/phishing#98](https://github.com/mitchellkrogza/phishing/pull/98)
> 
> PS: did you got time to have a peak on the readme's over at https://mypdns.org/clefspeare13/pornhosts

Not really. I have been busy
